baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'contem.'

# hugo
enableEmoji = true
enableInlineShortcodes = false
paginate = 10

# custom
[params]
	tabTitle = "comtem.plate"
	enableRuleLine = true
	enableFooter = true
	titleHalf = "plate"
	logo = "🍽️"
	mySite="https://www.abhishekarya.com"
	

